chore(actions): enforce ubuntu-latest runners

diff --git a/.github/workflows/node.js-tests.yml b/.github/workflows/node.js-tests.yml
--- a/.github/workflows/node.js-tests.yml
+++ b/.github/workflows/node.js-tests.yml
@@ -1,270 +1,246 @@
 name: CI - Node.js
-
 on:
   push:
     branches:
-      - 'main'
-      - 'prod-**'
-      - 'renovate/**'
+    - main
+    - prod-**
+    - renovate/**
   pull_request:
     branches:
-      - 'main'
-      - 'temp-**' # Temporary branches allowed on Upstream
-
+    - main
+    - temp-**
 concurrency:
-  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.workflow_run.head_branch || github.ref }}
-  cancel-in-progress: ${{ !contains(github.ref, 'main') && !contains(github.ref, 'prod-') }}
-
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.workflow_run.head_branch
+    || github.ref }}
+  cancel-in-progress: ${{ !contains(github.ref, 'main') && !contains(github.ref, 'prod-')
+    }}
 permissions:
   contents: read
-
 jobs:
   lint:
     name: Lint
-    # Skip PR runs for Renovate since push already triggered CI
-    if: github.event_name != 'pull_request' || github.event.pull_request.user.login != 'renovate[bot]'
-    runs-on: ubuntu-24.04
+    if: github.event_name != 'pull_request' || github.event.pull_request.user.login
+      != 'renovate[bot]'
+    runs-on: ubuntu-latest
     strategy:
       matrix:
-        node-version: [24]
+        node-version:
+        - 24
       fail-fast: false
-
     steps:
-      - name: Checkout
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
-        with:
-          submodules: 'recursive'
+    - name: Checkout
+      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
+      with:
+        submodules: recursive
+    - name: Check number of lockfiles
+      run: "if [ $(find . -name 'package-lock.json' | grep -vc -e 'node_modules')\
+        \ -gt 0 ]\nthen\n  echo -e 'Error: found package-lock files in the repository.\\\
+        nWe use pnpm workspaces to manage packages so all dependencies should be added\
+        \ via pnpm add'\n  exit 1\nfi\n"
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
+      with:
+        node-version: ${{ matrix.node-version }}
+    - name: Install pnpm
+      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
+      id: pnpm-install
+      with:
+        run_install: false
+    - name: Set Environment variables
+      run: 'cp sample.env .env
 
-      - name: Check number of lockfiles
-        run: |
-          if [ $(find . -name 'package-lock.json' | grep -vc -e 'node_modules') -gt 0 ]
-          then
-            echo -e 'Error: found package-lock files in the repository.\nWe use pnpm workspaces to manage packages so all dependencies should be added via pnpm add'
-            exit 1
-          fi
+        cat .env
 
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
-        with:
-          node-version: ${{ matrix.node-version }}
+        '
+    - name: Install node_modules
+      run: pnpm install
+    - name: Check formatting
+      run: 'pnpm prettier --check . || [ $? -eq 1 ] && printf "\nTip: Run ''pnpm run
+        format'' in your terminal to fix this.\n\n"
 
-      - name: Install pnpm
-        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
-        id: pnpm-install
-        with:
-          run_install: false
+        '
+    - name: Lint Source Files
+      run: 'echo pnpm version $(pnpm -v)
 
-      - name: Set Environment variables
-        run: |
-          cp sample.env .env
-          cat .env
+        pnpm lint
 
-      - name: Install node_modules
-        run: pnpm install
-
-      - name: Check formatting
-        run: |
-          pnpm prettier --check . || [ $? -eq 1 ] && printf "\nTip: Run 'pnpm run format' in your terminal to fix this.\n\n"
-
-      # The two prefixed installs are for the client update which are not,
-      # currently, built as workspaces.
-      - name: Lint Source Files
-        run: |
-          echo pnpm version $(pnpm -v)
-          pnpm lint
-
-  # DONT REMOVE THIS JOB.
-  # TODO: Refactor and use re-usable workflow and shared artifacts
+        '
   build:
     name: Build
     needs: lint
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-latest
     strategy:
       matrix:
-        node-version: [24]
-
+        node-version:
+        - 24
     steps:
-      - name: Checkout
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
-        with:
-          submodules: 'recursive'
+    - name: Checkout
+      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
+      with:
+        submodules: recursive
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
+      with:
+        node-version: ${{ matrix.node-version }}
+    - name: Install pnpm
+      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
+      id: pnpm-install
+      with:
+        run_install: false
+    - name: Set freeCodeCamp Environment Variables
+      run: 'cp sample.env .env
 
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
-        with:
-          node-version: ${{ matrix.node-version }}
+        '
+    - name: Install and Build
+      run: 'pnpm install
 
-      - name: Install pnpm
-        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
-        id: pnpm-install
-        with:
-          run_install: false
+        pnpm run build
 
-      - name: Set freeCodeCamp Environment Variables
-        run: |
-          cp sample.env .env
-
-      - name: Install and Build
-        run: |
-          pnpm install
-          pnpm run build
-
+        '
   test:
     name: Test
     needs: build
-    runs-on: ubuntu-24.04
-
+    runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        node-version: [24]
-
+        node-version:
+        - 24
     steps:
-      - name: Checkout
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
-        with:
-          submodules: 'recursive'
+    - name: Checkout
+      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
+      with:
+        submodules: recursive
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
+      with:
+        node-version: ${{ matrix.node-version }}
+    - name: Install pnpm
+      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
+      id: pnpm-install
+      with:
+        run_install: false
+    - name: Set Environment variables
+      run: 'cp sample.env .env
 
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
-        with:
-          node-version: ${{ matrix.node-version }}
+        cat .env
 
-      - name: Install pnpm
-        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
-        id: pnpm-install
-        with:
-          run_install: false
+        '
+    - name: Start MongoDB
+      run: docker compose -f docker/docker-compose.yml up -d
+    - name: Install Dependencies
+      run: 'echo pnpm version $(pnpm -v)
 
-      - name: Set Environment variables
-        run: |
-          cp sample.env .env
-          cat .env
+        pnpm install
 
-      - name: Start MongoDB
-        run: docker compose -f docker/docker-compose.yml up -d
-
-      - name: Install Dependencies
-        run: |
-          echo pnpm version $(pnpm -v)
-          pnpm install
-
-      - name: Install Chrome for Puppeteer
-        run: pnpm -F=curriculum install-puppeteer
-
-      - name: Run Tests
-        run: pnpm test
-
+        '
+    - name: Install Chrome for Puppeteer
+      run: pnpm -F=curriculum install-puppeteer
+    - name: Run Tests
+      run: pnpm test
   test-upcoming:
     name: Test - Upcoming Changes
     needs: build
-    runs-on: ubuntu-24.04
-
+    runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        node-version: [24]
-
+        node-version:
+        - 24
     steps:
-      - name: Checkout
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
-        with:
-          submodules: 'recursive'
+    - name: Checkout
+      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
+      with:
+        submodules: recursive
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
+      with:
+        node-version: ${{ matrix.node-version }}
+    - name: Install pnpm
+      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
+      id: pnpm-install
+      with:
+        run_install: false
+    - name: Set Environment variables
+      run: 'cp sample.env .env
 
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
-        with:
-          node-version: ${{ matrix.node-version }}
+        echo ''SHOW_UPCOMING_CHANGES=true'' >> .env
 
-      - name: Install pnpm
-        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
-        id: pnpm-install
-        with:
-          run_install: false
+        cat .env
 
-      - name: Set Environment variables
-        run: |
-          cp sample.env .env
-          echo 'SHOW_UPCOMING_CHANGES=true' >> .env
-          cat .env
+        '
+    - name: Start MongoDB
+      run: docker compose -f docker/docker-compose.yml up -d
+    - name: Install Dependencies
+      run: 'echo pnpm version $(pnpm -v)
 
-      - name: Start MongoDB
-        run: docker compose -f docker/docker-compose.yml up -d
+        pnpm install
 
-      - name: Install Dependencies
-        run: |
-          echo pnpm version $(pnpm -v)
-          pnpm install
-
-      - name: Install Chrome for Puppeteer
-        run: pnpm -F=curriculum install-puppeteer
-
-      - name: Run Tests
-        run: pnpm test
-
+        '
+    - name: Install Chrome for Puppeteer
+      run: pnpm -F=curriculum install-puppeteer
+    - name: Run Tests
+      run: pnpm test
   test-localization:
     name: Test - i18n
     needs: build
-    runs-on: ubuntu-24.04
-    if: github.event.pull_request.user.login == 'camperbot' && github.head_ref == 'chore/update-i18n-curriculum-submodule'
-
+    runs-on: ubuntu-latest
+    if: github.event.pull_request.user.login == 'camperbot' && github.head_ref ==
+      'chore/update-i18n-curriculum-submodule'
     strategy:
       fail-fast: false
       matrix:
-        node-version: [24]
-        locale: [portuguese, italian]
-
+        node-version:
+        - 24
+        locale:
+        - portuguese
+        - italian
     steps:
-      - name: Checkout
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
-        with:
-          submodules: 'recursive'
+    - name: Checkout
+      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
+      with:
+        submodules: recursive
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
+      with:
+        node-version: ${{ matrix.node-version }}
+    - name: Install pnpm
+      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
+      id: pnpm-install
+      with:
+        run_install: false
+    - name: Set Environment variables
+      run: 'cp sample.env .env
 
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
-        with:
-          node-version: ${{ matrix.node-version }}
+        cat .env
 
-      - name: Install pnpm
-        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
-        id: pnpm-install
-        with:
-          run_install: false
+        '
+    - name: Start MongoDB
+      uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94
+      with:
+        mongodb-version: 8.0
+        mongodb-replica-set: test-rs
+        mongodb-port: 27017
+    - name: Install Dependencies
+      env:
+        CURRICULUM_LOCALE: ${{ matrix.locale }}
+        CLIENT_LOCALE: ${{ matrix.locale }}
+      run: 'echo pnpm version $(pnpm -v)
 
-      - name: Set Environment variables
-        run: |
-          cp sample.env .env
-          cat .env
+        pnpm install
 
-      - name: Start MongoDB
-        uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94 # 1.12.1
-        with:
-          mongodb-version: 8.0
-          mongodb-replica-set: test-rs
-          mongodb-port: 27017
+        '
+    - name: Build Client in ${{ matrix.locale }}
+      env:
+        CURRICULUM_LOCALE: ${{ matrix.locale }}
+        CLIENT_LOCALE: ${{ matrix.locale }}
+      run: 'pnpm run build
 
-      - name: Install Dependencies
-        env:
-          CURRICULUM_LOCALE: ${{ matrix.locale }}
-          CLIENT_LOCALE: ${{ matrix.locale }}
-        run: |
-          echo pnpm version $(pnpm -v)
-          pnpm install
-
-      # DONT REMOVE THIS STEP.
-      # TODO: Refactor and use re-usable workflow and shared artifacts
-      - name: Build Client in ${{ matrix.locale }}
-        env:
-          CURRICULUM_LOCALE: ${{ matrix.locale }}
-          CLIENT_LOCALE: ${{ matrix.locale }}
-        run: |
-          pnpm run build
-
-      - name: Install Chrome for Puppeteer
-        run: pnpm -F=curriculum install-puppeteer
-
-      - name: Run Tests
-        env:
-          CURRICULUM_LOCALE: ${{ matrix.locale }}
-          CLIENT_LOCALE: ${{ matrix.locale }}
-        run: pnpm test
+        '
+    - name: Install Chrome for Puppeteer
+      run: pnpm -F=curriculum install-puppeteer
+    - name: Run Tests
+      env:
+        CURRICULUM_LOCALE: ${{ matrix.locale }}
+        CLIENT_LOCALE: ${{ matrix.locale }}
+      run: pnpm test
